# To auto build what we need.

before_install:
  - "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-xetex latex-xcolor texlive-fonts-recommended texlive-latex-extra lmodern texlive-latex-recommended"
  - "sudo apt-get install ttf-wqy-microhei ttf-wqy-zenhei"


script:
  - cd Documents
  - xelatex APIDoc.tex
  - xelatex ArchitectureDesign.tex
  - xelatex DemandAnalysis.tex
  - xelatex TestReport.tex

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git config --global user.name "travis_auto"
    git config --global user.email "qinka@live.com"
    echo "config done"
    cd ~
    eval "$(ssh-agent -s)"
    cat $DEPLOY_KEY > .travis/deploy_key.pem
    chmod 600 .travis/deploy_key.pem
    ssh-add .travis/deploy_key.pem
    git clone git@github.com:XDUDsTeam/YrarbilRelease.git
    echo "clone done"
    cd YrarbilRelease
    export RELPATH=$(pwd)
    cd "$TRAVIS_BUILD_DIR"/Documents
    ls
    pwd
    cp *.pdf $RELPATH
    echo "copy done"
    cd $RELPATH
    git add .
    git commit -am"$(date)"
    echo "commit done"
    git push origin master
    cd ~
    sudo rm -rf $RELPATH
    cd "$TRAVIS_BUILD_DIR"
  fi
