# To auto build what we need.

before_install:
  - "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-xetex latex-xcolor texlive-fonts-recommended texlive-latex-extra lmodern texlive-latex-recommended"
  - "sudo apt-get install ttf-wqy-microhei ttf-wqy-zenhei"


script:
  - cd Documents
  - xelatex APIDoc.tex
  - xelatex ArchitectureDesign.tex
  - xelatex DemandAnalysis.tex
  - xelatex TestReport.tex

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git config --global user.name "travis_auto"
    git config --global user.email "qinka@live.com"
    echo "config done"
    cd ~
    pwd
    git clone https://github.com/XDUDsTeam/YrarbilRelease.git
    echo "clone done"
    cd YrarbilRelease
    export RELPATH=$(pwd)s
    cd "$TRAVIS_BUILD_DIR"/Documents
    ls
    pwd
    cp *.pdf $RELAPTH
    echo "copy done"
    cd $RELPATH
    git add .
    git commit -am"$(date)"
    echo "commit done"
    echo "qinka@live.com" > git_push.in
    echo $GITHUB_API_KEY >> git_push.in
    git push origin master < git_push.in
    cd ..
    rm -r $RELPATH
    cd "$TRAVIS_BUILD_DIR"
  fi
