# To auto build what we need.

before_install:
  - "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-xetex latex-xcolor texlive-fonts-recommended texlive-latex-extra lmodern texlive-latex-recommended"
  - "sudo apt-get install ttf-wqy-microhei ttf-wqy-zenhei"


script:
  - cd Documents
  - xelatex APIDoc.tex
  - xelatex ArchitectureDesign.tex
  - xelatex DemandAnalysis.tex
  - xelatex TestReport.tex

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    echo http;//Qinka:$GITHUB_API_KEY@github.com > ~/.git-credentials
    git config --global user.name "travis_auto"
    git config --global user.email "qinka@live.com"
    git config --global credential.helper store
    echo "config done"
    cd "$TRAVIS_BUILD_DIR"/Documents
    ls
    pwd
    git clone https://github.com/XDUDsTeam/YrarbilRelease.git
    echo "clone done"
    cp *.pdf YrarbilRelease/
    echo "copy done"
    git add .
    git commit -am"$(date)"
    echo "commit done"
    git push origin master
    cd "$TRAVIS_BUILD_DIR"
  fi
