# To auto build what we need.

before_install:
  - "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-xetex latex-xcolor texlive-fonts-recommended texlive-latex-extra lmodern texlive-latex-recommended"
  - "sudo apt-get install ttf-wqy-microhei ttf-wqy-zenhei"


script:
  - cd Documents
  - xelatex APIDoc.tex
  - xelatex ArchitectureDesign.tex
  - xelatex DemandAnalysis.tex
  - xelatex TestReport.tex

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"/Documents
    ls
    pwd
    git clone https://github.com/XDUDsTeam/YrarbilRelease.git
    git config --global user.name "travis_auto"
    git config --global user.email "qinka@live.com"
    cp *.pdf YrarbilRelease/
    git add .
    git commit -am"$(date)"
    git push -f -q https://Qinka:$GITHUB_API_KEY@github.com/XDUDsTeam/YrarbilRelease.git-master master &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
